# Generated by Django 4.2.19 on 2025-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='extra',
            field=models.TextField(default=2),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='extra2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
