# Generated by Django 4.2.19 on 2025-03-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_extra_userinfo_extra2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='extra2',
        ),
    ]
